const rawData = [
  {
    Id: 1,
    "Chemical Name": "Acetone",
    Vendor: "ABC Company",
    Density: 0.7893,
    Viscosity: 0.3,
    Packaging: "Drum",
    "Pack Size": 200,
    Unit: "kg",
    Quantity: 5,
  },
  {
    Id: 2,
    "Chemical Name": "Ethanol",
    Vendor: "XYZ Inc.",
    Density: 0.789,
    Viscosity: 0.5,
    Packaging: "Barrel",
    "Pack Size": 100,
    Unit: "L",
    Quantity: 3,
  },
  {
    Id: 3,
    "Chemical Name": "Sulfuric Acid",
    Vendor: "PQR Ltd.",
    Density: 1.84,
    Viscosity: 1.2,
    Packaging: "IBC",
    "Pack Size": 1000,
    Unit: "kg",
    Quantity: 1,
  },
  {
    Id: 4,
    "Chemical Name": "Methanol",
    Vendor: "ABC Company",
    Density: 0.7918,
    Viscosity: 0.6,
    Packaging: "Drum",
    "Pack Size": 200,
    Unit: "kg",
    Quantity: 7,
  },
  {
    Id: 5,
    "Chemical Name": "Hydrogen Peroxide",
    Vendor: "XYZ Inc.",
    Density: 1.12,
    Viscosity: 1.0,
    Packaging: "Barrel",
    "Pack Size": 100,
    Unit: "L",
    Quantity: 2,
  },
  {
    Id: 6,
    "Chemical Name": "Ammonia",
    Vendor: "PQR Ltd.",
    Density: 0.771,
    Viscosity: 0.3,
    Packaging: "IBC",
    "Pack Size": 1000,
    Unit: "kg",
    Quantity: 1,
  },
  {
    Id: 7,
    "Chemical Name": "Chloroform",
    Vendor: "ABC Company",
    Density: 1.48,
    Viscosity: 0.6,
    Packaging: "Drum",
    "Pack Size": 200,
    Unit: "kg",
    Quantity: 5,
  },
  {
    Id: 8,
    "Chemical Name": "Carbon Tetrachloride",
    Vendor: "XYZ Inc.",
    Density: 1.595,
    Viscosity: 0.7,
    Packaging: "Barrel",
    "Pack Size": 100,
    Unit: "L",
    Quantity: 3,
  },
  {
    Id: 9,
    "Chemical Name": "Sodium Hydroxide",
    Vendor: "PQR Ltd.",
    Density: 2.13,
    Viscosity: 1.2,
    Packaging: "IBC",
    "Pack Size": 1000,
    Unit: "kg",
    Quantity: 1,
  },
  {
    Id: 10,
    "Chemical Name": "Ethylene Glycol",
    Vendor: "ABC Company",
    Density: 1.113,
    Viscosity: 1.6,
    Packaging: "Drum",
    "Pack Size": 200,
    Unit: "kg",
    Quantity: 4,
  },
  {
    Id: 11,
    "Chemical Name": "Nitric Acid",
    Vendor: "XYZ Inc.",
    Density: 1.42,
    Viscosity: 1.1,
    Packaging: "Barrel",
    "Pack Size": 100,
    Unit: "L",
    Quantity: 2,
  },
  {
    Id: 12,
    "Chemical Name": "Phosphoric Acid",
    Vendor: "PQR Ltd.",
    Density: 1.88,
    Viscosity: 1.4,
    Packaging: "IBC",
    "Pack Size": 1000,
    Unit: "kg",
    Quantity: 1,
  },
  {
    Id: 13,
    "Chemical Name": "Toluene",
    Vendor: "ABC Company",
    Density: 0.867,
    Viscosity: 0.6,
    Packaging: "Drum",
    "Pack Size": 200,
    Unit: "kg",
    Quantity: 6,
  },
  {
    Id: 14,
    "Chemical Name": "Methyl Ethyl Ketone",
    Vendor: "XYZ Inc.",
    Density: 0.805,
    Viscosity: 0.4,
    Packaging: "Barrel",
    "Pack Size": 100,
    Unit: "L",
    Quantity: 4,
  },
  {
    Id: 15,
    "Chemical Name": "Hydrochloric Acid",
    Vendor: "PQR Ltd.",
    Density: 1.18,
    Viscosity: 0.9,
    Packaging: "IBC",
    "Pack Size": 1000,
    Unit: "kg",
    Quantity: 1,
  },
];
